### PR TITLE
don't skip cleanup

### PR DESCRIPTION
**Pull request by jaakkor2**
Try to remove interference between the platform builds, could help for https://github.com/JuliaGeo/LibGEOS.jl/pull/56

### CODE REVIEW

**Comment by jaakkor2** [comment]
Close for now

**Comment by visr** [comment]
Thanks for thinking along! Has this been a problem for other Builders as well? The reason the new GEOS build is not working on Win64 now is also reported here: https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/407.

**Comment by jaakkor2** [comment]
I was planning to test `make clean` as well, but I could not get Travis to generate binaries for my fork.  Would trying only Win64 build make sense?

**Comment by visr** [comment]
Yes you can run only the Win64 build. I don't think the reason for the issues is contamination between the environments, but rather issues with mixing compiler versions. We could for instance try to split out the GCC versions in the GEOSBuilder, and try using GCC7, like in https://github.com/JuliaPackaging/BinaryProvider.jl/issues/152

For development it is also convenient to build locally on Linux, with

```
julia --color=yes build_tarballs.jl --verbose --debug x86_64-w64-mingw32
```

**Pull request closed without merging**
